apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name : blue-green-ingress
  namespace: blue-green-rollout
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: blue-green-testing.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: active-svc
            port:
              number: 80
